version: '2'

services:
  zookeeper:
    build: 
      context: ./zookeeper
    image: frank/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888"
      - "3888"
  kafka:
    build:
      context: ./kafka
    image: frank/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.223
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    depends_on:
      - zookeeper
